---
after_script:
- rake travis:after -t
before_script:
- gem install hoe-travis --no-document
- rake travis:before -t
language: ruby
notifications:
  email:
  - drbrain@segment7.net
rvm:
- 2.1.0 # minimum supported
- 2.2
- 2.3
- 2.4
- 2.5
- 2.6
script: rake travis
